### PR TITLE
Move spec to AsciiDoc

### PR DESCRIPTION
**Pull request by wmat**
PR for change to AsciiDoc.

### CODE REVIEW

**Comment by IainCRobertson** [comment]
Hi Jeff.  I reviewed the Asciidoc version of the spec with Bill prior to this PR, but it wasn't clear to me who was responsible for merging this.  I can review, and if I'm happy that it is an accurate transformation from LaTeX, are you happy for me to just merge, or does someone else need to bless it off?

**Comment by wmat** [comment]
Feel free to merge, Iain.

Bill Traynor
Documentation Build and Release Engineer
RISC-V International

**Comment by IainCRobertson** [comment]
Reviewed and looks okay.

**Comment by IainCRobertson** [comment]
Done 😊.

I assume you or Jeff will take care of publishing and updating the Technical Specification page to link to the new asciidoc based PDF?

Iain

**Comment by wmat** [comment]
Yes, we’ll take care of that.

Bill Traynor
Documentation Build and Release Engineer
RISC-V International

**Pull request merged**
