### PR TITLE
Formatting fixes

### PR DESCRIPTION
**Pull request by wmat**
Fixes issue #100

### CODE REVIEW

**Comment by IainCRobertson** [comment]
Looks good.  We will need to republish as 2.0.3.  Shouldn't that be part of the same PR?

**Comment by IainCRobertson** [comment]
Actually, there was a 3rd error related to missing pluses in the definition of the width of the irdepth field that also needs fixing.

**Comment by wmat** [comment]
Is the 3rd error another looplabel 4 typo?

**Comment by IainCRobertson** [comment]
No.  

return_stack_size_p (return_stack_size_p > 0 ? 1 : 0) call_counter_size_p 

should be 

return_stack_size_p + (return_stack_size_p > 0 ? 1 : 0) + call_counter_size_p

**Comment by wmat** [comment]
Fixed.

**Comment by IainCRobertson** [comment]
Thanks Bill.  Do you want to do the revision history and version changes as a separate PR?  Not obvious why we should separate them.

**Comment by wmat** [comment]
Oh right.  I can update it here.

**Comment by IainCRobertson** [comment]
Thanks Bill.  Sorry to be a pain but we also need a comment in the revision history table.

**Comment by IainCRobertson** [comment]
Thanks Bill.  I assume you and Jeff will take care of getting this published?

**Pull request merged**
